### ISSUE TITLE
Soundbar Error

### ISSUE THREAD

**Issue by Caswell1000** [macbury/ha_samsung_multi_room#1]
Hi,

Thanks for the files and configuration, I have a [Samsung Soundbar](http://www.samsung.com/uk/support/model/HT-E8200/XU), saved the python file as instructed under "\\Rp2\home assistant\custom_components\media_player" I added the Soundbar to the configuration.yaml file as follows:

```
media_player:
  - platform: cast
  - platform: samsung_multiroom
    name:
    host: 192.168.1.101
    max_volume: 40

``` 

I get an error that indicates samsung_multi_room is not found. 
 

> Log Details (ERROR)
Sat May 19 2018 22:07:30 GMT+0200 (South Africa Standard Time)
Platform not found: media_player.samsung_multiroom
