### ISSUE TITLE
Platform error media_player.samsung_multi_room - Integration 'samsung_multi_room' not found.

### ISSUE THREAD

**Issue by lowrisk75** [macbury/ha_samsung_multi_room#10]
I'm new to Home Assistant and I'm petty sure the issue is coming from me.

I copy the file to` config/custom_components/media_player/`

but I keep having this error :
**Platform error media_player.samsung_multi_room - Integration 'samsung_multi_room' not found.**

PS the first media_player platform is for a another components 
```
media_player:
  - platform: samsungtv_tizen
    host: 192.168.X.XX
    mac: XX:XX:XX:XX:XX:XX
  - platform: samsung_multi_room
    name: "Soundbar"  
    host: 192.168.X.XX 
    max_volume: 20 
```
